[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         tail
    Path         /tmp/openroad_*.log
    Tag          openroad
    Read_from_Head true



[FILTER]
    Name         grep
    Match        openroad
    Regex        message (Reading|initialize_floorplan|Starting|complete|Writing)

[OUTPUT]
    Name         file
    Match        openroad
    Path         /tmp/
    File         openroad_stages.json
    Format       json_lines
