[SERVICE]
    Flush        1
    Log_Level    info
    Daemon       off
    Parsers_File parsers.conf

[INPUT]
    Name         tail
    Path         openroad_output/*.log
    Parser       openroad
    Tag          openroad
    Refresh_Interval 1
    Read_from_Head true
    
[FILTER]
    Name         grep
    Match        openroad
    Regex        message (Starting|complete|Reading|Writing|Executing)
    
[OUTPUT]
    Name         stdout
    Match        openroad
